--- #YAML:1.0
name:               IO-Pager
version:            0.3
abstract:           Select a pager and pipe text to it if destination is a TTY
author:
    - Jerrad Pierce <jpierce@cpan.org>, Florent Angly <florent.angly@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Config:      0
    Env:         0
    Exporter:    0
    File::Temp:  0
    Test::More:  0
requires:
    base:         0
    Config:       0
    Env:          0
    Exporter:     0
    File::Spec:   0
    File::Temp:   0
    File::Which:  0
    IO::Handle:   0
    PerlIO:       0
    SelectSaver:  0
    Symbol:       0
    Test::More:   0
    Tie::Handle:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
